"use client";

import { useEffect, useState } from "react";
import { DeviceChart, DailyChart, TrafficChart } from "@/components/admin/Charts";

type Item = { name: string; value: number };
type Stats = { cards: { visitors: number; sessions: number; pageViews: number; leads: number; liveUsers: number; conversionRate: number }; sources: Item[]; channels: Item[]; campaigns: Item[]; devices: Item[]; countries: Item[]; daily: { date: string; value: number }[]; recentEvents: any[]; recentSessions: any[] };
const empty: Stats = { cards: { visitors: 0, sessions: 0, pageViews: 0, leads: 0, liveUsers: 0, conversionRate: 0 }, sources: [], channels: [], campaigns: [], devices: [], countries: [], daily: [], recentEvents: [], recentSessions: [] };
const metricLabels: Array<[keyof Stats["cards"], string, string]> = [["visitors", "Unique visitors", "Last 30 days"], ["liveUsers", "Live now", "Active in the last 35 seconds"], ["pageViews", "Page views", "Last 30 days"], ["sessions", "Sessions", "Last 30 days"], ["leads", "Leads", "Form submissions"], ["conversionRate", "Conversion", "Leads per session"]];

export default function AdminOverview() {
  const [data, setData] = useState<Stats>(empty); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { let active = true; const load = async () => { try { const response = await fetch("/api/admin/stats", { cache: "no-store" }); if (!response.ok) throw new Error("Unable to load analytics"); if (active) setData(await response.json()); setError(""); } catch (e: any) { if (active) setError(e.message); } finally { if (active) setLoading(false); } }; load(); const timer = window.setInterval(load, 15000); return () => { active = false; clearInterval(timer); }; }, []);
  return <div className="dashboard">
    <div className="admin-top dashboard-hero"><div><div className="crumb">Analytics workspace / Overview</div><h1>Know what brings people in.</h1><p>Live acquisition, visitor context and landing-page performance in one view.</p></div><div className="refresh"><span className="status-dot" /> Live refresh every 15 seconds</div></div>
    {error && <div className="dashboard-alert">{error}. Check your MongoDB connection and credentials.</div>}
    <div className="stat-grid stat-grid-rich">{metricLabels.map(([key, label, hint]) => <div className="stat-card" key={key}><span>{label}</span><strong>{loading ? "—" : key === "conversionRate" ? `${data.cards[key]}%` : data.cards[key]}</strong><small>{hint}</small></div>)}</div>
    <div className="panel panel-feature"><div className="panel-head"><div><p className="panel-kicker">Engagement trend</p><h2>Daily page views</h2><p>See which days create momentum on your landing page.</p></div></div><div className="chart-large"><DailyChart items={data.daily}/></div></div>
    <div className="three-col"><div className="panel"><p className="panel-kicker">Attribution</p><h2>Traffic sources</h2><div className="chart-box"><TrafficChart items={data.sources}/></div></div><div className="panel"><p className="panel-kicker">Channel mix</p><h2>How they found you</h2>{data.channels.length ? data.channels.map(x => <div className="bar-row" key={x.name}><span>{x.name}</span><b>{x.value}</b></div>) : <div className="empty">Campaign and referrer data will appear here.</div>}</div><div className="panel"><p className="panel-kicker">Audience</p><h2>Device mix</h2><div className="chart-box"><DeviceChart items={data.devices}/></div></div></div>
    <div className="two-col"><div className="panel"><p className="panel-kicker">Campaign intelligence</p><h2>Top campaigns</h2>{data.campaigns.length ? data.campaigns.map(x => <div className="bar-row" key={x.name}><span>{x.name}</span><b>{x.value} sessions</b></div>) : <div className="empty">Tag ad links with UTM values to compare campaigns.</div>}</div><div className="panel"><p className="panel-kicker">Live activity</p><h2>Recent events</h2>{data.recentEvents.length ? data.recentEvents.map((x: any) => <div className="activity-row" key={String(x._id)}><span className="activity-dot" /><div><b>{String(x.type).replaceAll("_", " ")}</b><small>{x.page || "/"} · {new Date(x.createdAt).toLocaleString()}</small></div></div>) : <div className="empty">Visitor activity will appear here.</div>}</div></div>
    <div className="panel table-wrap"><div className="panel-head"><div><p className="panel-kicker">Visitor intelligence</p><h2>Latest sessions</h2></div></div><table><thead><tr><th>Visitor</th><th>IP address</th><th>Acquisition</th><th>Campaign</th><th>Landing page</th><th>Platform</th><th>Activity</th></tr></thead><tbody>{data.recentSessions.map((s: any) => <tr key={String(s._id)}><td>{s.city || "Unknown"}, {s.country || "Unknown"}</td><td className="mono">{s.ip || "Unavailable"}</td><td><b>{s.source || "Direct"}</b><br /><small>{s.channel || s.medium || "Direct"}</small></td><td>{s.campaign || "—"}</td><td className="truncate-cell" title={s.landingPage}>{s.landingPage || "/"}</td><td>{s.device || "—"} · {s.browser || "—"}<br /><small>{s.os || "—"}</small></td><td>{s.pageCount || 0} pages · {Math.round(s.duration || 0)}s</td></tr>)}</tbody></table>{!data.recentSessions.length && <div className="empty">No sessions recorded yet.</div>}</div>
  </div>;
}
